import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { writeFile, mkdtemp, stat } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
const server=spawn('python',['-m','http.server','8791','--directory','wwwroot'],{stdio:'ignore'});
let browser;
try{
  browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});
  const page=await context.newPage();
  page.on('console',m=>console.log('Browser '+m.type()+':',m.text().slice(0,500)));page.on('requestfailed',r=>console.log('Request failed:',r.url(),r.failure()?.errorText));page.on('pageerror',e=>console.log('Page error:',e.message));
  await page.goto('http://127.0.0.1:8791/',{waitUntil:'networkidle'});
  await page.getByRole('button',{name:'Abrir exemplo com Player'}).click();
  await page.locator('#run').click();
  await page.waitForFunction(()=>Number(document.querySelector('#canvas')?.dataset.frames)>4 || ['Erro no jogo','Revise os erros de compilação'].includes(document.querySelector('#runtimeStatus')?.textContent),null,{timeout:120000});
  console.log('Status:',await page.locator('#runtimeStatus').textContent(),'Diagnostics:',(await page.locator('#diagnostics').innerText()).slice(0,1600));
  if (Number(await page.locator('#canvas').getAttribute('data-frames'))<5) throw Error('O exemplo C# não desenhou cinco quadros.');
  await page.waitForFunction(()=>Number(document.querySelector('#canvas').dataset.frames)>4,{timeout:15000});
  console.log('Compiled two C# files and drew',await page.locator('#canvas').getAttribute('data-frames'),'frames');
  const [download]=await Promise.all([page.waitForEvent('download',{timeout:60000}),page.locator('#exportGame').click()]);
  const directory=await mkdtemp(path.join(os.tmpdir(),'forge-'));
  const file=path.join(directory,'export.html');await download.saveAs(file);
  console.log('Exported:',(await stat(file)).size,'bytes');
  const offline=await browser.newContext({viewport:{width:390,height:844},permissions:[]});
  await offline.route('**/*',route=>{if(!route.request().url().startsWith('file://')&&!route.request().url().startsWith('blob:'))route.abort();else route.continue();});
  const game=await offline.newPage();
  game.on('console',m=>{if(m.type()==='error')console.log('Export browser:',m.text().slice(0,500));});
  await game.goto('file://'+file);
  await game.locator('canvas[data-frames]').waitFor({timeout:180000});
  await game.waitForFunction(()=>Number(document.querySelector('canvas').dataset.frames)>4,{timeout:15000});
  console.log('Offline standalone:',await game.locator('canvas').getAttribute('data-frames'),'frames');
  if(await game.locator('#error').isVisible())throw Error(await game.locator('#error').innerText());
  await offline.close();
  await page.locator('[data-view=code]').click();
  await page.getByRole('button',{name:'Player.cs'}).click();
  await page.locator('.cm-content').focus();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.type('\nINVALID_C_SHARP');
  await page.locator('#run').click();
  await page.getByText(/Player.cs:\d+:/).first().waitFor({timeout:180000});
  console.log('Invalid C# diagnostic tied to Player.cs');
  await context.close();
}catch(e){console.error(e);process.exitCode=1;}finally{await browser?.close();server.kill();}
