import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { execFileSync } from 'node:child_process';
import { mkdir, mkdtemp, stat } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
const server=spawn('python',['-m','http.server','8791','--directory','wwwroot'],{stdio:'ignore'});
let browser;
try{
  await mkdir('out/ux',{recursive:true});
  browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});
  const page=await context.newPage();
  page.on('console',m=>console.log('Browser '+m.type()+':',m.text().slice(0,500)));page.on('requestfailed',r=>console.log('Request failed:',r.url(),r.failure()?.errorText));page.on('pageerror',e=>console.log('Page error:',e.message));
  await page.goto('http://127.0.0.1:8791/',{waitUntil:'networkidle'});
  await page.screenshot({path:'out/ux/01-projects.png'});
  await page.locator('#newProject').click();
  await page.locator('#dialogInput').fill('Projeto vazio');
  await page.locator('#nameDialog button[value=ok]').click();
  const template=await page.locator('.cm-content').innerText();
  if(!['void Start()','void Update(float dt)','void Draw()'].every(x=>template.includes(x)) || await page.locator('#tabs button').count()!==1)throw Error('Template inicial deixou de ser mínimo.');
  await page.locator('#focusMode').click();
  if(await page.locator('.bottom-nav').isVisible())throw Error('Modo foco não liberou espaço.');
  await page.locator('#focusExit').click();
  await page.locator('#homeButton').click();
  await page.getByRole('button',{name:'Abrir exemplo com Player'}).click();
  await page.screenshot({path:'out/ux/02-code.png'});
  await page.locator('#projectMenuToggle').click();
  await page.locator('#codeWrap').check();
  await page.locator('#closeActions').click();
  await page.locator('#filesToggle').click();
  await page.locator('#fileSearch').fill('Player');
  await page.locator('#fileTree button').filter({hasText:'Player.cs'}).click();
  await page.locator('#fileMenuToggle').click();
  await page.locator('#renameFile').click();
  await page.locator('#dialogInput').fill('Actors/Player.cs');
  await page.locator('#nameDialog button[value=ok]').click();
  await page.locator('#filesToggle').click();
  if(await page.locator('#fileTree details summary').filter({hasText:'Actors'}).count()!==1)throw Error('Explorador não organizou arquivo em pasta.');
  await page.locator('#closeExplorer').click();
  await page.locator('.cm-content').focus();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.type('\n// HISTORIA_DO_ARQUIVO');
  await page.getByRole('button',{name:'MainGame.cs'}).click();
  await page.getByRole('button',{name:'Player.cs'}).click();
  if(!(await page.locator('.cm-content').innerText()).includes('HISTORIA_DO_ARQUIVO'))throw Error('Troca de arquivo perdeu alterações.');
  await page.locator('.cm-content').focus();await page.keyboard.press('ControlOrMeta+z');
  await page.waitForFunction(()=>!document.querySelector('.cm-content').textContent.includes('HISTORIA_DO_ARQUIVO'));
  await page.locator('[data-view=sprites]').click();
  if(await page.locator('#tabs').isVisible()||await page.locator('.filebar').isVisible())throw Error('Ferramentas de código vazaram para a área de arte.');
  await page.getByRole('button',{name:'hero'}).click();
  await page.locator('#spriteColor').fill('#ff3456');
  await page.locator('#spriteCanvas').click({position:{x:5,y:5}});
  await page.screenshot({path:'out/ux/03-art.png'});
  await page.locator('#spriteZoom').fill('2');
  await page.locator('#spritePan').click();
  if(await page.locator('#spriteCanvas').getAttribute('data-pan')!=='true')throw Error('Navegação do canvas não ativou.');
  await page.locator('#spritePencil').click();
  await page.locator('#spriteZoom').fill('1');
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('A interface transborda horizontalmente no celular.');
  const pixel=await page.locator('#spriteCanvas').evaluate(canvas=>[...canvas.getContext('2d').getImageData(0,0,1,1).data]);
  if(pixel[0]!==255||pixel[1]!==52||pixel[2]!==86)throw Error('Editor de sprites não alterou o pixel.');
  const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=2;canvas.height=2;canvas.getContext('2d').fillRect(0,0,2,2);return canvas.toDataURL('image/png').split(',')[1];});
  await page.locator('#spriteInput').setInputFiles({name:'bonus.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
  await page.locator('#dialogInput').fill('bonus');
  await page.locator('#nameDialog button[value=ok]').click();
  await page.getByText('2 × 2 pixels').waitFor();
  if(await page.locator('#spriteList button').count()!==2)throw Error('PNG não foi importado como sprite.');
  await page.locator('#newSheet').click();
  await page.locator('#dialogInput').fill('tiles');
  await page.locator('#nameDialog button[value=ok]').click();
  await page.waitForFunction(()=>document.querySelectorAll('#spriteTiles button').length===16,null,{timeout:5000});
  await page.locator('#spriteColor').fill('#33cc88');
  await page.locator('#spriteCanvas').click({position:{x:5,y:5}});
  await page.locator('#assetsMaps').click();
  await page.locator('#newMap').click();
  await page.locator('#dialogInput').fill('level');
  await page.locator('#nameDialog button[value=ok]').click();
  await page.getByText('20 × 20 células').waitFor();
  await page.locator('#mapWorkspace .inspector summary').click();
  await page.locator('#mapSheet').selectOption('tiles');
  await page.locator('#mapWorkspace .inspector summary').click();
  await page.locator('#mapCanvas').click({position:{x:5,y:5}});
  await page.screenshot({path:'out/ux/04-map.png'});
  await page.locator('[data-view=code]').click();
  await page.getByRole('button',{name:'MainGame.cs'}).click();
  await page.locator('.cm-line').filter({hasText:'Player.Draw();'}).click();
  await page.keyboard.press('Home');
  await page.keyboard.type('Graphics.Tilemap("level", 200, 0);');
  await page.keyboard.press('Enter');
  await page.locator('#run').click();
  await page.waitForFunction(()=>Number(document.querySelector('#canvas')?.dataset.frames)>4 || ['Erro no jogo','Revise os erros de compilação'].includes(document.querySelector('#runtimeStatus')?.textContent),null,{timeout:120000});
  console.log('Status:',await page.locator('#runtimeStatus').textContent(),'Diagnostics:',(await page.locator('#diagnostics').innerText()).slice(0,1600));
  if (Number(await page.locator('#canvas').getAttribute('data-frames'))<5) throw Error('O exemplo C# não desenhou cinco quadros.');
  const spriteVisible=await page.locator('#canvas').evaluate(canvas=>[...canvas.getContext('2d').getImageData(32,80,1,1).data]);
  if(spriteVisible[0]!==255||spriteVisible[1]!==52||spriteVisible[2]!==86)throw Error('Sprite editado não apareceu na prévia C#.');
  const mapPixel=await page.locator('#canvas').evaluate(canvas=>[...canvas.getContext('2d').getImageData(200,0,1,1).data]);
  if(mapPixel[0]!==51||mapPixel[1]!==204||mapPixel[2]!==136)throw Error('Tilemap não apareceu na prévia C#.');
  const box=await page.locator('#canvas').boundingBox();
  await page.mouse.move(box.x+box.width*180/360,box.y+box.height*300/640);
  await page.mouse.down();
  await page.waitForFunction(()=>{
    const canvas=document.querySelector('#canvas'),rgba=canvas.getContext('2d').getImageData(156,276,1,1).data;
    return rgba[0]===255 && rgba[1]===52 && rgba[2]===86;
  },null,{timeout:10000});
  await page.mouse.up();
  console.log('Touch moved C# Player and preserved sprite pixels');
  await page.waitForFunction(()=>Number(document.querySelector('#canvas').dataset.frames)>4,{timeout:15000});
  console.log('Compiled two C# files and drew',await page.locator('#canvas').getAttribute('data-frames'),'frames');
  const [download]=await Promise.all([page.waitForEvent('download',{timeout:60000}),page.locator('#exportGame').click()]);
  const directory=await mkdtemp(path.join(os.tmpdir(),'forge-'));
  const file=path.join(directory,'export.zip');await download.saveAs(file);
  console.log('Exported:',(await stat(file)).size,'bytes');
  execFileSync('unzip',['-t',file]);
  const names=execFileSync('unzip',['-Z1',file],{encoding:'utf8'}).trim().split('\n');
  if(names.sort().join(',')!==['game-data.js','game.js','index.html','runtime-data.js'].sort().join(',')||names.some(name=>name.includes('/')))throw Error('ZIP contém arquivos fora da raiz ou ausentes.');
  execFileSync('unzip',['-q',file,'-d',directory]);
  const offline=await browser.newContext({viewport:{width:390,height:844},permissions:[]});
  await offline.route('**/*',route=>{if(!route.request().url().startsWith('file://')&&!route.request().url().startsWith('blob:'))route.abort();else route.continue();});
  const game=await offline.newPage();
  game.on('console',m=>{if(m.type()==='error')console.log('Export browser:',m.text().slice(0,500));});
  await game.goto('file://'+path.join(directory,'index.html'));
  await game.locator('canvas[data-frames]').waitFor({timeout:180000});
  await game.waitForFunction(()=>Number(document.querySelector('canvas').dataset.frames)>4,{timeout:15000});
  console.log('Offline standalone:',await game.locator('canvas').getAttribute('data-frames'),'frames');
  const exportedPixel=await game.locator('canvas').evaluate(canvas=>[...canvas.getContext('2d').getImageData(32,80,1,1).data]);
  if(exportedPixel[0]!==255||exportedPixel[1]!==52||exportedPixel[2]!==86)throw Error('O sprite editado não foi exportado.');
  const exportedMap=await game.locator('canvas').evaluate(canvas=>[...canvas.getContext('2d').getImageData(200,0,1,1).data]);
  if(exportedMap[0]!==51||exportedMap[1]!==204||exportedMap[2]!==136)throw Error('O tilemap não foi exportado.');
  if(await game.locator('#error').isVisible())throw Error(await game.locator('#error').innerText());
  await offline.close();
  await page.locator('[data-view=code]').click();
  await page.getByRole('button',{name:'Player.cs'}).click();
  await page.locator('.cm-content').focus();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.type('\nINVALID_C_SHARP');
  await page.locator('#run').click();
  await page.getByText(/Actors\/Player.cs:\d+:/).first().waitFor({timeout:180000});
  console.log('Invalid C# diagnostic tied to Actors/Player.cs');
  await page.locator('#homeButton').click();
  await page.getByRole('button',{name:'Testar controles e UI'}).click();
  await page.locator('[data-view=guide]').click();
  await page.locator('#frameworkTabs button').filter({hasText:'UI.cs'}).click();
  await page.locator('#frameworkViewer .cm-content').getByText('public static class UI').waitFor();
  if(await page.locator('#frameworkViewer .cm-content').getAttribute('contenteditable')!=='false')throw Error('Biblioteca deveria ser somente leitura.');
  await page.locator('#run').click();
  await page.waitForFunction(()=>Number(document.querySelector('#canvas').dataset.frames)>4 || document.querySelector('#runtimeStatus').textContent.includes('erro'),null,{timeout:120000});
  console.log('Controls status:',await page.locator('#runtimeStatus').textContent(),'Diagnostics:',(await page.locator('#diagnostics').innerText()).slice(0,800));
  await page.locator('.mobileforge-ui button').first().waitFor();
  const getPosition=()=>page.locator('#canvas').evaluate(canvas=>{const ctx=canvas.getContext('2d');for(let x=0;x<330;x++){const d=ctx.getImageData(x,280,1,1).data;if(d[0]===128&&d[1]===230&&d[2]===185)return x;}return -1;});
  const before=await getPosition();
  await page.locator('.mobileforge-ui button').last().click();
  await page.waitForFunction(old=>{const c=document.querySelector('#canvas'),ctx=c.getContext('2d');return ctx.getImageData(old+20,280,1,1).data[0]===128;},before);
  const clicked=await getPosition();if(clicked<before+20)throw Error('onClick não moveu o jogo C#.');
  await page.locator('.mobileforge-ui input[type=range]').fill('300');
  const right=page.locator('.mobileforge-ui button').nth(1);const bounds=await right.boundingBox();await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);await page.mouse.down();
  await page.waitForTimeout(250);await page.mouse.up();
  const after=await getPosition();if(after<=clicked)throw Error('onPress e slider não moveram o jogo.');
  console.log('UI actions moved rectangle:',before,clicked,after);

  await context.close();
}catch(e){console.error(e);process.exitCode=1;}finally{await browser?.close();server.kill();}
