import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { copyFile, mkdir, mkdtemp, stat } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
const server=spawn('python',['-m','http.server','8791','--directory','wwwroot'],{stdio:'ignore'});
let browser;
try{
  browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});
  const page=await context.newPage();
  page.on('console',m=>console.log('Browser '+m.type()+':',m.text().slice(0,500)));page.on('requestfailed',r=>console.log('Request failed:',r.url(),r.failure()?.errorText));page.on('pageerror',e=>console.log('Page error:',e.message));
  await page.goto('http://127.0.0.1:8791/',{waitUntil:'networkidle'});
  await page.locator('#newProject').click();
  await page.locator('#dialogInput').fill('Projeto vazio');
  await page.locator('#nameDialog button[value=ok]').click();
  const template=await page.locator('.cm-content').innerText();
  if(!['void Start()','void Update(float dt)','void Draw()'].every(x=>template.includes(x)) || await page.locator('#tabs button').count()!==1)throw Error('Template inicial deixou de ser mínimo.');
  await page.locator('#homeButton').click();
  await page.getByRole('button',{name:'Abrir exemplo com Player'}).click();
  await page.locator('[data-view=sprites]').click();
  await page.getByRole('button',{name:'hero'}).click();
  await page.locator('#spriteColor').fill('#ff3456');
  await page.locator('#spriteCanvas').click({position:{x:5,y:5}});
  const pixel=await page.locator('#spriteCanvas').evaluate(canvas=>[...canvas.getContext('2d').getImageData(0,0,1,1).data]);
  if(pixel[0]!==255||pixel[1]!==52||pixel[2]!==86)throw Error('Editor de sprites não alterou o pixel.');
  const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=2;canvas.height=2;canvas.getContext('2d').fillRect(0,0,2,2);return canvas.toDataURL('image/png').split(',')[1];});
  await page.locator('#spriteInput').setInputFiles({name:'bonus.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
  await page.locator('#dialogInput').fill('bonus');
  await page.locator('#nameDialog button[value=ok]').click();
  await page.getByText('2 × 2 pixels').waitFor();
  if(await page.locator('#spriteList button').count()!==2)throw Error('PNG não foi importado como sprite.');
  await page.locator('#run').click();
  await page.waitForFunction(()=>Number(document.querySelector('#canvas')?.dataset.frames)>4 || ['Erro no jogo','Revise os erros de compilação'].includes(document.querySelector('#runtimeStatus')?.textContent),null,{timeout:120000});
  console.log('Status:',await page.locator('#runtimeStatus').textContent(),'Diagnostics:',(await page.locator('#diagnostics').innerText()).slice(0,1600));
  if (Number(await page.locator('#canvas').getAttribute('data-frames'))<5) throw Error('O exemplo C# não desenhou cinco quadros.');
  const spriteVisible=await page.locator('#canvas').evaluate(canvas=>[...canvas.getContext('2d').getImageData(32,80,1,1).data]);
  if(spriteVisible[0]!==255||spriteVisible[1]!==52||spriteVisible[2]!==86)throw Error('Sprite editado não apareceu na prévia C#.');
  const box=await page.locator('#canvas').boundingBox();
  await page.mouse.move(box.x+box.width*180/360,box.y+box.height*300/640);
  await page.mouse.down();
  await page.waitForFunction(()=>{
    const canvas=document.querySelector('#canvas'),rgba=canvas.getContext('2d').getImageData(156,276,1,1).data;
    return rgba[0]===255 && rgba[1]===52 && rgba[2]===86;
  },null,{timeout:10000});
  await page.mouse.up();
  console.log('Touch moved C# Player and preserved sprite pixels');
  await page.waitForFunction(()=>Number(document.querySelector('#canvas').dataset.frames)>4,{timeout:15000});
  console.log('Compiled two C# files and drew',await page.locator('#canvas').getAttribute('data-frames'),'frames');
  const [download]=await Promise.all([page.waitForEvent('download',{timeout:60000}),page.locator('#exportGame').click()]);
  const directory=await mkdtemp(path.join(os.tmpdir(),'forge-'));
  const file=path.join(directory,'export.html');await download.saveAs(file);
  console.log('Exported:',(await stat(file)).size,'bytes');
  const offline=await browser.newContext({viewport:{width:390,height:844},permissions:[]});
  await offline.route('**/*',route=>{if(!route.request().url().startsWith('file://')&&!route.request().url().startsWith('blob:'))route.abort();else route.continue();});
  const game=await offline.newPage();
  game.on('console',m=>{if(m.type()==='error')console.log('Export browser:',m.text().slice(0,500));});
  await game.goto('file://'+file);
  await game.locator('canvas[data-frames]').waitFor({timeout:180000});
  await game.waitForFunction(()=>Number(document.querySelector('canvas').dataset.frames)>4,{timeout:15000});
  console.log('Offline standalone:',await game.locator('canvas').getAttribute('data-frames'),'frames');
  const exportedPixel=await game.locator('canvas').evaluate(canvas=>[...canvas.getContext('2d').getImageData(32,80,1,1).data]);
  if(exportedPixel[0]!==255||exportedPixel[1]!==52||exportedPixel[2]!==86)throw Error('O sprite editado não foi exportado.');
  if(await game.locator('#error').isVisible())throw Error(await game.locator('#error').innerText());
  if(process.env.FORGE_APK_SAMPLE){
    const target=path.resolve(process.env.FORGE_APK_SAMPLE);
    await mkdir(path.dirname(target),{recursive:true});
    await copyFile(file,target);
    console.log('Android sample prepared:',target);
  }
  await offline.close();
  await page.locator('[data-view=code]').click();
  await page.getByRole('button',{name:'Player.cs'}).click();
  await page.locator('.cm-content').focus();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.type('\nINVALID_C_SHARP');
  await page.locator('#run').click();
  await page.getByText(/Player.cs:\d+:/).first().waitFor({timeout:180000});
  console.log('Invalid C# diagnostic tied to Player.cs');
  await context.close();
}catch(e){console.error(e);process.exitCode=1;}finally{await browser?.close();server.kill();}
